name: Build
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
jobs:
  build-swift:
    uses: ./.github/workflows/build-swift.yml
    with:
      node_version: '20.x'

  build-wasm:
    needs: build-swift
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree-sitter-wasms-cline
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: swift-parser-src
          path: swift-parser

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 2.0.24

      - name: Patch tree-sitter modules
        run: pnpm patch-modules

      - name: Build tree-sitter WASM
        run: pnpm build
